### ISSUE TITLE
[Overall] Add metadata to events.json

### ISSUE THREAD

**Issue by bluenex** [titipata/penn-events-calendar#103]
We use `event_index` to track selected and recommended events by saving them to `localStorage` of the browser. This works fine because we only append more events to the file. However, when we need to refresh the data after some time, `event_index` will no longer be the same anymore. This will cause incorrect results of search and recommendation.

To solve this we will add metadata to the `events.json`:

```json
{
  "name": "...",
  "refresh_count": 1,
  "fetch_date": "...", 
  "modified_date": "",
  "data": ["list_of_events"],
}
```

- `refresh_count`:  increase only when `fetch_date` updated once every 1-2 years
- `fetch_date`:  date of the first fetch date
- `modified_date`: this is updated regularly (weekly) but it should be `""` when `first_date` updated
- `data`: a list of events

**Comment by titipata** [comment]
I don't think we need `data` here. We can create a simple script to see the list of all events.

**Comment by bluenex** [comment]
What do you mean by simple script?

This structure is a replacement of a current `events.json`. `data` actually contains the whole content from  current `events.json`.

**Comment by titipata** [comment]
Oh, I got it. I misunderstood. Already change the data format in #100

**Comment by titipata** [comment]
This issue will be resolved in #100. We only need to fix the reader in the front-end.

**Comment by titipata** [comment]
@bluenex note here that we should clear the cache when the data is newly fetched (i.e. `modified_date` is an empty string)?

**Comment by bluenex** [comment]
@titipata so as we discussed earlier, we need to check 2 keys to clear the cache correctly. 

- when the `modified_date` is an empty string
- when the `refresh_count` (or `reset_count`) is changed - this key is also saved to `localStorage` and used to compare on next load.

With that, `refresh_count` should be updated only when the whole file is fetched (maybe after a year or two).
