### ISSUE TITLE
[Devops] Supervisor is not able to kill forked processes

### ISSUE THREAD

**Issue by bluenex** [titipata/penn-events-calendar#104]
We notice that once we run the program `supervisor-elasticsearch`, it runs correctly. However, when we try to stop it, only the parent process is killed leaving the child processes running indefinitely. 

We may be able to resolve this with `stopasgroup` option as mentioned in https://stackoverflow.com/a/20566215/4010864.

**Comment by titipata** [comment]
This should be fixed in #106. Can we close this issue?

**Comment by bluenex** [comment]
sure!
