### ISSUE TITLE
[Devops] Create a service on AWS or Digital Ocean

### ISSUE THREAD

**Issue by titipata** [titipata/penn-events-calendar#107]
- [x] Create a server with permanent (elastic) IP
- [ ] Ask IT (or ISC) at Penn to associate the domain name to the IP (waiting for MindCORE to grant temporary domain name)

**Comment by bluenex** [comment]
Demo is ready on http://52.43.144.62 after #115. Next step is to get the domain name.

**Comment by titipata** [comment]
@bluenex now, we are waiting for the IT department to set up a new AWS for us. We will set up and migrate to the new server (maybe in `t2.large`). Doing this, we will also have a new IP address for the demo.

**Comment by titipata** [comment]
The demo should be at at http://35.160.123.103/ now. Fetch events and create features work fine on `t3.large` instance from Amazon. I will close this issue since we only have to wait for the domain name.
