### ISSUE TITLE
[Frontend] Clear localStorage for outlier ``event_index``

### ISSUE THREAD

**Issue by titipata** [titipata/penn-events-calendar#109]
We have to clear the localStorage if we observe outlier `event_index`. This can happen when the data is updated and the former localStorage still stores the previous `event_index` which might exceed index in the dataset.

**Comment by bluenex** [comment]
@titipata this approach has a crucial flaw. If the newly fetched data has the `event_index` more than what presented in the local storage, the local storage will not be cleared and we would get the wrong data to render.

However, this can be used as a foolproof. Let's discuss more about this. In the meantime I think #103 can be closed.

**Comment by bluenex** [comment]
- add foolproof.
- if there are too many events the frontend can handle, we will revise graphql query on Gatsby pages.

**Comment by bluenex** [comment]
A foolproof is added in backend (29876fd) in #113. This can be closed. @titipata 👀
