### ISSUE TITLE
[Frontend] optimize load time on first load

### ISSUE THREAD

**Issue by bluenex** [titipata/penn-events-calendar#130]
Possible solutions:

- use [react-virtualized](https://bvaughn.github.io/react-virtualized/#/components/List) to lazy load list.
- implement a true pagination using GraphQL as suggested by [Gatsby docs](https://www.gatsbyjs.org/docs/adding-pagination/).
- change response of endpoints to include requested data.

**Comment by titipata** [comment]
Closed via #132
