### ISSUE TITLE
Adding social media share for Twitter and Facebook

### ISSUE THREAD

**Issue by titipata** [titipata/penn-events-calendar#135]
See how to add `meta` for Facebook and Twitter below

- Facebook: https://developers.facebook.com/docs/sharing/webmasters/
- Twitter: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

Gatsby: https://www.gatsbyjs.org/packages/gatsby-remark-social-cards/

Blog: https://juliangaramendy.dev/custom-open-graph-images-in-gatsby-blog/

**Comment by titipata** [comment]
`og-title` - Events at Penn
`og-description` -  A web application that collects all events happening at the University of Pennsylvania with built-in search and recommendation engine.
`og-image` - attached above
`og:url` - `http://35.160.123.103/`
`og:site_name` - `http://35.160.123.103/`


<img width="921" alt="social-share" src="https://user-images.githubusercontent.com/8295838/68611686-ae075180-0488-11ea-9b5a-5b46186eaac5.png">

**Comment by bluenex** [comment]
More resource(s):

- https://www.gatsbyjs.org/docs/add-page-metadata/

**Comment by titipata** [comment]
Still waiting for the `og` to show up: https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2F35.160.123.103%2F

**Comment by titipata** [comment]
I think #142 and #143 should solve this issue. Now, it's ready to share via http://bit.ly/2Qd8xBz or http://35.160.123.103/.
