### ISSUE TITLE
[devops] Restart Gatsby and hug after fetching events

### ISSUE THREAD

**Issue by titipata** [titipata/penn-events-calendar#138]
It seems that the data on the site does not get updated after new data is fetched. Moreover, `hug` backend does not know how to re-read the data after it gets updated. Is there a way for `supervisord` to restart Gatsby and hug after the new data is fetched?

**Comment by titipata** [comment]
Moreover, we can run `supervisor-grobid` only when we scrape the sites. Otherwise, we can stop it since it takes over a lot of fo memory.

**Comment by bluenex** [comment]
Sure you may need to search for:

1. how can you run `supervisorctl` of the `penn-events` env without having to `source activate`.
2. run that `supervisorctl` with `restart supervisor-hug` option.
3. make sure that you can run (2) within `schedule_fetch_events`. I think it is possible via `subprocess`.
4. with (3) you can control which process to run and when to stop and run again.

**Comment by titipata** [comment]
Close via #139.
