### ISSUE TITLE
[Backend] improve functionality and fix bug

### ISSUE THREAD

**Issue by bluenex** [titipata/penn-events-calendar#53]
- [x] Fetch MindCORE events
- [x] Fix "Invalid date"
- [x] allow recommendation sort by relevances/ timeline
- [x] reduce recommendation size to 15

**Comment by bluenex** [comment]
> allow recommendation sort by relevances/ timeline

We agreed to sort by date and render relevance in the star. I think we can close this? @titipata

**Comment by titipata** [comment]
@bluenex, yeah, I think we can close this for now. We will use the relevance indication in the star for now.
