### ISSUE TITLE
[Frontend/Backend] Elasticsearch completion suggester

### ISSUE THREAD

**Issue by titipata** [titipata/penn-events-calendar#74]
Implement completion suggester feature from elasticsearch

Reference:
-  https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#completion-suggester
- https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#completion-suggester
- https://kb.objectrocket.com/mongo-db/how-to-use-python-to-update-api-elasticsearch-documents-259

```python
es.update(
    index='penn-events',
    id=1,
    doc_type='event',
    body={
        'doc':{
            'suggest': ['Pratik Chaudhari', 'Barchi']
        }
    },
    refresh=True,
)
```

Then for loop through all events and update.

```python
doc = {
    'size' : 10000,
    'query': {
        'match_all' : {}
    }
}
indices = [int(r['_id']) for r in es.search(
    index='penn-events', 
    body=doc,
    scroll='1m'
)['hits']['hits']]
```

To search events

```python
suggest_body = {
    "suggest": {
        "field-suggest" : {
            "prefix" : "prati", 
            "completion" : { 
                "field" : "suggest" 
            }
        }
    }
}
es.search(index='penn-events', body=suggest_body)
```

**Workflow**:
- user type search text in the frontend
- then, suggest all titles coming from backend
- allow them to click on one of the search result
- take the event index to search result page, get recommendation of that particular event
- list under the search one label `You may also interested in ...`

**Comment by bluenex** [comment]
done via #75.
