### ISSUE TITLE
[Backend] Remove duplicate event after run fetch_events

### ISSUE THREAD

**Issue by titipata** [titipata/penn-events-calendar#91]
Currently, we use the following [script](https://github.com/titipata/penn-events-calendar/blob/master/backend/fetch_events.py#L2284-L2289) to remove duplicates. We should group by owner (except a few) and remove duplicates by URL and get last scraped events instead.

**Comment by bluenex** [comment]
@titipata how is this progress? Any reference to and PR or branch?

**Comment by bluenex** [comment]
@titipata can you elaborate what we were discussing before? About fuzzy match/hash of several fields (title, date, starttime, url). Just to make sure that we won't forget 😛

**Comment by titipata** [comment]
The finalized version is using `['owner', 'title', 'date_dt', 'starttime']` [here](https://github.com/titipata/penn-events-calendar/blob/master/backend/fetch_events.py#L2504) to aggregate events. It works decently well if the title doesn't change. We can close the issue and re-open later or we can also leave it open too.
